/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMain: typeof import('./layout/components/AppMain.vue')['default']
    Avatar: typeof import('./components/Avatar/index.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
    Counter: typeof import('./components/Counter/index.vue')['default']
    ElBreadcrum: typeof import('element-plus/es')['ElBreadcrum']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElBreadcurmbItem: typeof import('element-plus/es')['ElBreadcurmbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDorpdown: typeof import('element-plus/es')['ElDorpdown']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconProvider: typeof import('@element-plus/icons-vue')['Provider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElSwitich: typeof import('element-plus/es')['ElSwitich']
    ElSwtich: typeof import('element-plus/es')['ElSwtich']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Hambuger: typeof import('./components/Hambuger/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logo: typeof import('./layout/components/Sidebar/Logo.vue')['default']
    Navbar: typeof import('./layout/components/Navbar.vue')['default']
    RightPanel: typeof import('./components/RightPanel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./components/Screenfull/index.vue')['default']
    ScrollPanel: typeof import('./components/TagsView/ScrollPanel.vue')['default']
    Settings: typeof import('./components/Settings/index.vue')['default']
    Sidebar: typeof import('./layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./layout/components/Sidebar/SidebarItem.vue')['default']
    SidebarItemLink: typeof import('./layout/components/Sidebar/SidebarItemLink.vue')['default']
    SizeSelect: typeof import('./components/SizeSelect/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TagsView: typeof import('./components/TagsView/index.vue')['default']
    ThemePicker: typeof import('./components/ThemePicker/index.vue')['default']
  }
}
